print("=== Aplikasi Biodata===")
print("")
nama = input ("masukan nama anda: ")
kampus = input ("masukan nama kampus :")
angkatan = input ("masukan angkatan :")
semester = input ("masukan semester :")
prodi = input ("masukan program studi :")
nim = input ("masukan NIM anda :")

print("==== Welcome Biodata ====")
print("Nama             : ", nama)
print("Kampus           : ", kampus)
print("Angkatan         : ", angkatan)
print("Semester         : ", semester)
print("Program Studi    : ", prodi)
print("NIM              : ", nim)